// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "goods-manager/internal/domain/entity"

	mock "github.com/stretchr/testify/mock"
)

// LoggerUsecase is an autogenerated mock type for the LoggerUsecase type
type LoggerUsecase struct {
	mock.Mock
}

// SaveList provides a mock function with given fields: ctx, goods
func (_m *LoggerUsecase) SaveList(ctx context.Context, goods []*entity.Good) error {
	ret := _m.Called(ctx, goods)

	if len(ret) == 0 {
		panic("no return value specified for SaveList")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []*entity.Good) error); ok {
		r0 = rf(ctx, goods)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SendToQueue provides a mock function with given fields: ctx, good
func (_m *LoggerUsecase) SendToQueue(ctx context.Context, good *entity.Good) error {
	ret := _m.Called(ctx, good)

	if len(ret) == 0 {
		panic("no return value specified for SendToQueue")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Good) error); ok {
		r0 = rf(ctx, good)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewLoggerUsecase creates a new instance of LoggerUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLoggerUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *LoggerUsecase {
	mock := &LoggerUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
