// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "goods-manager/internal/domain/entity"

	mock "github.com/stretchr/testify/mock"
)

// LoggerRepository is an autogenerated mock type for the LoggerRepository type
type LoggerRepository struct {
	mock.Mock
}

// SaveList provides a mock function with given fields: ctx, goods
func (_m *LoggerRepository) SaveList(ctx context.Context, goods []*entity.Good) error {
	ret := _m.Called(ctx, goods)

	if len(ret) == 0 {
		panic("no return value specified for SaveList")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []*entity.Good) error); ok {
		r0 = rf(ctx, goods)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewLoggerRepository creates a new instance of LoggerRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLoggerRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *LoggerRepository {
	mock := &LoggerRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
